DROP TABLE IF EXISTS BRAND;
DROP TABLE IF EXISTS COLOR;
DROP TABLE IF EXISTS PRODUCTCAT;
DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE BRAND( 
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(250) NOT NULL);

CREATE TABLE COLOR(
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(250) NOT NULL,
CODE VARCHAR(10) NOT NULL);

CREATE TABLE PRODUCTCAT(
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(250) NOT NULL);

CREATE TABLE PRODUCT(
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(250) NOT NULL,
QUANTITY INT NOT NULL,
SIZE VARCHAR(10) NOT NULL,
PRICE INT NOT NULL,
BRAND_ID INT NOT NULL,
FOREIGN KEY(BRAND_ID) REFERENCES BRAND(ID),
CLR_ID INT NOT NULL,
FOREIGN KEY (CLR_ID) REFERENCES COLOR(ID),
PRODUCT_CAT_ID INT NOT NULL,
FOREIGN KEY (PRODUCT_CAT_ID) REFERENCES PRODUCTCAT(ID));
